/*
 * modelenums.h
 *
 *  Created on: 11.06.2009
 *      Author: Bastian
 */

#ifndef MODELENUMS_H_
#define MODELENUMS_H_

enum GlobalModelFlags{
	Global_Tilt_X	=	0x1,
	Global_Tilt_Y	=	0x2,
	Global_unk1	=	0x4,
	Global_AdditionalField	=	0x8,
	Global_unk2	=	0x10
};

enum InterpolationType{
	IT_None =0,
	IT_Linear =1,
	IT_Hermite =2,
	IT_Bezier =3
};

enum AnimationFlags{
	Anim_Every_Sequence	=	0x20//One thing I saw in the source is that "-1 animationblocks" in bones wont get parsed if 0x20 is not set.
};

enum BoneFlags{
	Bone_Billboarded	=	0x8,
	Bone_Transformed	=	0x200
};

enum RenderFlags{
	Render_Unlit	=	0x1,
	Render_Unfogged	=	0x2,
	Render_Two_Sided	=	0x4,
	Render_Billboarded	=	0x8, //???
	Render_Disable_Z_Buff	=	0x10 //???
};

enum BlendModes{
	Blend_Opaque	=	0,
	Blend_Mod	=	1,
	Blend_Decal	=	2,
	Blend_Add	=	3,
	Blend_Mod2x	=	4,
	Blend_Fade	=	5,
	Blend_Deeprun	=	6
};

enum LightTypes{
	Light_Directional	=	0,
	Light_Point	=	1
};

enum CameraTypes{
	Camera_Nothing	=	-1,
	Camera_Potrait	=	0,
	Camera_CharInfo	=	1
};

enum ParticleFlags{
	Particle_Do_Not_Trail	=	0x10,
	Particle_Do_Not_Billboard	=	0x1000
};


enum AnimationType {
    A_Stand = 0,
    A_Death,
    A_Spell,
    A_Stop,
    A_Walk,
    A_Run,
    A_Dead,
    A_Rise,
    A_StandWound,
    A_CombatWound,
    A_CombatCritical,
    A_ShuffleLeft,
    A_ShuffleRight,
    A_Walkbackwards,
    A_Stun,
    A_HandsClosed,
    A_AttackUnarmed,
    A_Attack1H,
    A_Attack2H,
    A_Attack2HL,
    A_ParryUnarmed,
    A_Parry1H,
    A_Parry2H,
    A_Parry2HL,
    A_ShieldBlock,
    A_ReadyUnarmed,
    A_Ready1H,
    A_Ready2H,
    A_Ready2HL,
    A_ReadyBow,
    A_Dodge,
    A_SpellPrecast,
    A_SpellCast,
    A_SpellCastArea,
    A_NPCWelcome,
    A_NPCGoodbye,
    A_Block,
    A_JumpStart,
    A_Jump,
    A_JumpEnd,
    A_Fall,
    A_SwimIdle,
    A_Swim,
    A_SwimLeft,
    A_SwimRight,
    A_SwimBackwards,
    A_AttackBow,
    A_FireBow,
    A_ReadyRifle,
    A_AttackRifle,
    A_Loot,
    A_ReadySpellDirected,
    A_ReadySpellOmni,
    A_SpellCastDirected,
    A_SpellCastOmni,
    A_BattleRoar,
    A_ReadyAbility,
    A_Special1H,
    A_Special2H,
    A_ShieldBash,
    A_EmoteTalk,
    A_EmoteEat,
    A_EmoteWork,
    A_EmoteUseStanding,
    A_EmoteTalkExclamation,
    A_EmoteTalkQuestion,
    A_EmoteBow,
    A_EmoteWave,
    A_EmoteCheer,
    A_EmoteDance,
    A_EmoteLaugh,
    A_EmoteSleep,
    A_EmoteSitGround,
    A_EmoteRude,
    A_EmoteRoar,
    A_EmoteKneel,
    A_EmoteKiss,
    A_EmoteCry,
    A_EmoteChicken,
    A_EmoteBeg,
    A_EmoteApplaud,
    A_EmoteShout,
    A_EmoteFlex,
    A_EmoteShy,
    A_EmotePoint,
    A_Attack1HPierce,
    A_Attack2HLoosePierce,
    A_AttackOff,
    A_AttackOffPierce,
    A_Sheath,
    A_HipSheath,
    A_Mount,
    A_RunRight,
    A_RunLeft,
    A_MountSpecial,
    A_Kick,
    A_SitGroundDown,
    A_SitGround,
    A_SitGroundUp,
    A_SleepDown,
    A_Sleep,
    A_SleepUp,
    A_SitChairLow,
    A_SitChairMed,
    A_SitChairHigh,
    A_LoadBow,
    A_LoadRifle,
    A_AttackThrown,
    A_ReadyThrown,
    A_HoldBow,
    A_HoldRifle,
    A_HoldThrown,
    A_LoadThrown,
    A_EmoteSalute,
    A_KneelStart,
    A_KneelLoop,
    A_KneelEnd,
    A_AttackUnarmedOff,
    A_SpecialUnarmed,
    A_StealthWalk,
    A_StealthStand,
    A_Knockdown,
    A_EatingLoop,
    A_UseStandingLoop,
    A_ChannelCastDirected,
    A_ChannelCastOmni,
    A_Whirlwind,
    A_Birth,
    A_UseStandingStart,
    A_UseStandingEnd,
    A_CreatureSpecial,
    A_Drown,
    A_Drowned,
    A_FishingCast,
    A_FishingLoop,
    A_Fly,
    A_EmoteWorkNoSheathe,
    A_EmoteStunNoSheathe,
    A_EmoteUseStandingNoSheathe,
    A_SpellSleepDown,
    A_SpellKneelStart,
    A_SpellKneelLoop,
    A_SpellKneelEnd,
    A_Sprint,
    A_InFlight,
    A_Spawn,
    A_Close,
    A_Closed,
    A_Open,
    A_Opened,
    A_Destroy,
    A_Destroyed,
    A_Rebuild,
    A_Custom0,
    A_Custom1,
    A_Custom2,
    A_Custom3,
    A_Despawn,
    A_Hold,
    A_Decay,
    A_BowPull,
    A_BowRelease,
    A_ShipStart,
    A_ShipMoving,
    A_ShipStop,
    A_GroupArrow,
    A_Arrow,
    A_CorpseArrow,
    A_GuideArrow,
    A_Sway,
    A_DruidCatPounce,
    A_DruidCatRip,
    A_DruidCatRake,
    A_DruidCatRavage,
    A_DruidCatClaw,
    A_DruidCatCower,
    A_DruidBearSwipe,
    A_DruidBearBite,
    A_DruidBearMaul,
    A_DruidBearBash,
    A_DragonTail,
    A_DragonStomp,
    A_DragonSpit,
    A_DragonSpitHover,
    A_DragonSpitFly,
    A_EmoteYes,
    A_EmoteNo,
    A_JumpLandRun,
    A_LootHold,
    A_LootUp,
    A_StandHigh,
    A_Impact,
    A_LiftOff,
    A_Hover,
    A_SuccubusEntice,
    A_EmoteTrain,
    A_EmoteDead,
    A_EmoteDanceOnce,
    A_Deflect,
    A_EmoteEatNoSheathe,
    A_Land,
    A_Submerge,
    A_Submerged,
    A_Cannibalize,
    A_ArrowBirth,
    A_GroupArrowBirth,
    A_CorpseArrowBirth,
    A_GuideArrowBirth,
    A_EmoteTalkNoSheathe,
    A_EmotePointNoSheathe,
    A_EmoteSaluteNoSheathe,
    A_EmoteDanceSpecial,
    A_Mutilate,
    A_CustomSpell01,
    A_CustomSpell02,
    A_CustomSpell03,
    A_CustomSpell04,
    A_CustomSpell05,
    A_CustomSpell06,
    A_CustomSpell07,
    A_CustomSpell08,
    A_CustomSpell09,
    A_CustomSpell10,
    A_StealthRun
};

enum ATTACHMENT_ID{
	At_Mountpoint_or_LeftWrist =0,
	At_Right_palm,
	At_Left_palm,
	At_Right_elbow,
	At_Left_elbow,
	At_Right_Shoulder,
	At_Left_Shoulder,
	At_Right_Knee,
	At_Left_knee,
	At_unk1,
	At_unk2,
	Helmet,
	At_Back,
	At_unk3,
	At_unk4,
	At_Bust,
	At_Bust2,
	At_Face,
	At_Above_Char,
	At_Ground,
	At_Top_of_head,
	At_Left_Palm2,
	At_Right_Palm2,
	At_unk5,
	At_unk6,
	At_nk7,
	At_Right_Back_Sheath,
	At_Left_Back_Sheath,
	At_Middle_Back_Sheath,
	At_Belly,
	At_Left_Back,
	At_Right_Back,
	At_Left_Hip_Sheath,
	At_Right_Hip_Sheath,
	At_Bust3,
	At_Right_Palm3
};

#endif /* MODELENUMS_H_ */
