/* Generated by Pyrex 0.9.3 on Sun Aug 21 01:49:28 2005 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#include "mpq.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
staticforward char **__pyx_f;

/* Declarations from mpq */

staticforward PyTypeObject __pyx_type_3mpq_Archive;

struct __pyx_obj_3mpq_Archive {
  PyObject_HEAD
  mpq_archive mpq_a;
};

staticforward PyTypeObject __pyx_type_3mpq_File;

struct __pyx_obj_3mpq_File {
  PyObject_HEAD
  mpq_file mpq_f;
  struct __pyx_obj_3mpq_Archive *archive;
  unsigned int size;
  int number;
};

static PyTypeObject *__pyx_ptype_3mpq_Archive = 0;
static PyTypeObject *__pyx_ptype_3mpq_File = 0;
static PyObject *__pyx_k1;

/* Implementation of mpq */

static PyObject *__pyx_n_IOError;

static PyObject *__pyx_k2p;

static char (__pyx_k2[]) = "unable to open archive: %s";

static int __pyx_f_3mpq_7Archive___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_3mpq_7Archive___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fn = 0;
  int __pyx_r;
  char (*__pyx_1);
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"fn",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_fn)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fn);

  /* "k:\wow\python\extract\src\mpq.pyx":44 */
  __pyx_1 = PyString_AsString(__pyx_v_fn); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
  __pyx_2 = (libmpq_archive_open((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),__pyx_1) < 0);
  if (__pyx_2) {

    /* "k:\wow\python\extract\src\mpq.pyx":45 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __pyx_4 = PyNumber_Remainder(__pyx_k2p, __pyx_v_fn); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    __Pyx_Raise(__pyx_3, __pyx_4, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("mpq.Archive.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fn);
  return __pyx_r;
}

static PyObject *__pyx_k3p;

static char (__pyx_k3[]) = "unable to read from file (number:%d, size:%d), errcode:%d";

static PyObject *__pyx_f_3mpq_7Archive_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3mpq_7Archive_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fn = 0;
  char (*__pyx_v_buf);
  int __pyx_v_fnum;
  int __pyx_v_size;
  int __pyx_v_ret;
  PyObject *__pyx_v_s;
  PyObject *__pyx_r;
  char (*__pyx_1);
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  static char *__pyx_argnames[] = {"fn",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_fn)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fn);
  __pyx_v_s = Py_None; Py_INCREF(__pyx_v_s);

  /* "k:\wow\python\extract\src\mpq.pyx":52 */
  __pyx_1 = PyString_AsString(__pyx_v_fn); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
  __pyx_v_fnum = libmpq_file_number((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),__pyx_1);

  /* "k:\wow\python\extract\src\mpq.pyx":53 */
  __pyx_v_size = libmpq_file_info((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),LIBMPQ_FILE_UNCOMPRESSED_SIZE,__pyx_v_fnum);

  /* "k:\wow\python\extract\src\mpq.pyx":54 */
  __pyx_v_buf = malloc(__pyx_v_size);

  /* "k:\wow\python\extract\src\mpq.pyx":55 */
  __pyx_v_ret = libmpq_file_getdata((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),__pyx_v_fnum,__pyx_v_buf);

  /* "k:\wow\python\extract\src\mpq.pyx":56 */
  __pyx_2 = (__pyx_v_ret < 0);
  if (__pyx_2) {

    /* "k:\wow\python\extract\src\mpq.pyx":57 */
    free(__pyx_v_buf);

    /* "k:\wow\python\extract\src\mpq.pyx":58 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_fnum); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_5 = PyInt_FromLong(__pyx_v_size); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_6 = PyInt_FromLong(__pyx_v_ret); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_7 = PyTuple_New(3); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_7, 0, __pyx_4);
    PyTuple_SET_ITEM(__pyx_7, 1, __pyx_5);
    PyTuple_SET_ITEM(__pyx_7, 2, __pyx_6);
    __pyx_4 = 0;
    __pyx_5 = 0;
    __pyx_6 = 0;
    __pyx_4 = PyNumber_Remainder(__pyx_k3p, __pyx_7); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    __Pyx_Raise(__pyx_3, __pyx_4, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "k:\wow\python\extract\src\mpq.pyx":59 */
  __pyx_5 = PyString_FromStringAndSize(__pyx_v_buf,__pyx_v_size); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
  Py_DECREF(__pyx_v_s);
  __pyx_v_s = __pyx_5;
  __pyx_5 = 0;

  /* "k:\wow\python\extract\src\mpq.pyx":60 */
  free(__pyx_v_buf);

  /* "k:\wow\python\extract\src\mpq.pyx":61 */
  Py_INCREF(__pyx_v_s);
  __pyx_r = __pyx_v_s;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("mpq.Archive.read");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fn);
  return __pyx_r;
}

static PyObject *__pyx_n_splitlines;

static PyObject *__pyx_k4p;

static char (__pyx_k4[]) = "unable to read from file (number:%d, size:%d), errcode:%d";

static PyObject *__pyx_f_3mpq_7Archive_namelist(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3mpq_7Archive_namelist(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char (*__pyx_v_buf);
  int __pyx_v_ret;
  PyObject *__pyx_v_fnum;
  PyObject *__pyx_v_size;
  PyObject *__pyx_v_s;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_fnum = Py_None; Py_INCREF(__pyx_v_fnum);
  __pyx_v_size = Py_None; Py_INCREF(__pyx_v_size);
  __pyx_v_s = Py_None; Py_INCREF(__pyx_v_s);

  /* "k:\wow\python\extract\src\mpq.pyx":66 */
  __pyx_1 = PyInt_FromLong((libmpq_archive_info((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),LIBMPQ_MPQ_NUMFILES) - 1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  Py_DECREF(__pyx_v_fnum);
  __pyx_v_fnum = __pyx_1;
  __pyx_1 = 0;

  /* "k:\wow\python\extract\src\mpq.pyx":67 */
  __pyx_2 = PyInt_AsLong(__pyx_v_fnum); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(libmpq_file_info((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),LIBMPQ_FILE_UNCOMPRESSED_SIZE,__pyx_2)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  Py_DECREF(__pyx_v_size);
  __pyx_v_size = __pyx_1;
  __pyx_1 = 0;

  /* "k:\wow\python\extract\src\mpq.pyx":68 */
  __pyx_2 = PyInt_AsLong(__pyx_v_size); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
  __pyx_v_buf = malloc(__pyx_2);

  /* "k:\wow\python\extract\src\mpq.pyx":69 */
  __pyx_2 = PyInt_AsLong(__pyx_v_fnum); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; goto __pyx_L1;}
  __pyx_v_ret = libmpq_file_getdata((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),__pyx_2,__pyx_v_buf);

  /* "k:\wow\python\extract\src\mpq.pyx":70 */
  __pyx_2 = (__pyx_v_ret < 0);
  if (__pyx_2) {

    /* "k:\wow\python\extract\src\mpq.pyx":71 */
    free(__pyx_v_buf);

    /* "k:\wow\python\extract\src\mpq.pyx":72 */
    __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_ret); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
    Py_INCREF(__pyx_v_fnum);
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_fnum);
    Py_INCREF(__pyx_v_size);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_v_size);
    PyTuple_SET_ITEM(__pyx_4, 2, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyNumber_Remainder(__pyx_k4p, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_1, __pyx_3, 0);
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "k:\wow\python\extract\src\mpq.pyx":73 */
  __pyx_2 = PyInt_AsLong(__pyx_v_size); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  __pyx_4 = PyString_FromStringAndSize(__pyx_v_buf,__pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  Py_DECREF(__pyx_v_s);
  __pyx_v_s = __pyx_4;
  __pyx_4 = 0;

  /* "k:\wow\python\extract\src\mpq.pyx":74 */
  free(__pyx_v_buf);

  /* "k:\wow\python\extract\src\mpq.pyx":75 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_s, __pyx_n_splitlines); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("mpq.Archive.namelist");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_fnum);
  Py_DECREF(__pyx_v_size);
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_3mpq_7Archive_close(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3mpq_7Archive_close(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":78 */
  libmpq_archive_close((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a));

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("mpq.Archive.close");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_3mpq_7Archive___contains__(PyObject *__pyx_v_self, PyObject *__pyx_v_fn); /*proto*/
static int __pyx_f_3mpq_7Archive___contains__(PyObject *__pyx_v_self, PyObject *__pyx_v_fn) {
  int __pyx_r;
  char (*__pyx_1);
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fn);

  /* "k:\wow\python\extract\src\mpq.pyx":91 */
  __pyx_1 = PyString_AsString(__pyx_v_fn); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_r = (libmpq_file_number((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),__pyx_1) != LIBMPQ_EFILE_NOT_FOUND);
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("mpq.Archive.__contains__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fn);
  return __pyx_r;
}

static PyObject *__pyx_n_close;

static PyObject *__pyx_f_3mpq_7Archive___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3mpq_7Archive___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":94 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_close); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("mpq.Archive.__del__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_3mpq_7Archive_4name___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_3mpq_7Archive_4name___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":98 */
  __pyx_1 = PyString_FromString(((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a.filename); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("mpq.Archive.name.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_3mpq_7Archive_9blocksize___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_3mpq_7Archive_9blocksize___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":102 */
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a.blocksize); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("mpq.Archive.blocksize.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_3mpq_7Archive_4size___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_3mpq_7Archive_4size___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":106 */
  __pyx_1 = PyInt_FromLong(libmpq_archive_info((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),LIBMPQ_MPQ_UNCOMPRESSED_SIZE)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("mpq.Archive.size.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_3mpq_7Archive_8numfiles___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_3mpq_7Archive_8numfiles___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":110 */
  __pyx_1 = PyInt_FromLong(libmpq_archive_info((&((struct __pyx_obj_3mpq_Archive *)__pyx_v_self)->mpq_a),LIBMPQ_MPQ_NUMFILES)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("mpq.Archive.numfiles.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k5p;

static char (__pyx_k5[]) = "unable to open file: %s";

static int __pyx_f_3mpq_4File___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_3mpq_4File___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fn = 0;
  struct __pyx_obj_3mpq_Archive *__pyx_v_archive = 0;
  int __pyx_v_fnum;
  int __pyx_r;
  char (*__pyx_1);
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"fn","archive",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_fn, &__pyx_v_archive)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fn);
  Py_INCREF(__pyx_v_archive);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_archive), __pyx_ptype_3mpq_Archive, 0, "archive")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}

  /* "k:\wow\python\extract\src\mpq.pyx":123 */
  __pyx_1 = PyString_AsString(__pyx_v_fn); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  __pyx_v_fnum = libmpq_file_number((&__pyx_v_archive->mpq_a),__pyx_1);

  /* "k:\wow\python\extract\src\mpq.pyx":124 */
  __pyx_2 = (__pyx_v_fnum != LIBMPQ_EFILE_NOT_FOUND);
  if (__pyx_2) {

    /* "k:\wow\python\extract\src\mpq.pyx":125 */
    Py_INCREF(((PyObject *)__pyx_v_archive));
    Py_DECREF(((PyObject *)((struct __pyx_obj_3mpq_File *)__pyx_v_self)->archive));
    ((PyObject *)((struct __pyx_obj_3mpq_File *)__pyx_v_self)->archive) = ((PyObject *)__pyx_v_archive);

    /* "k:\wow\python\extract\src\mpq.pyx":126 */
    ((struct __pyx_obj_3mpq_File *)__pyx_v_self)->number = __pyx_v_fnum;

    /* "k:\wow\python\extract\src\mpq.pyx":127 */
    ((struct __pyx_obj_3mpq_File *)__pyx_v_self)->size = libmpq_file_info((&__pyx_v_archive->mpq_a),LIBMPQ_FILE_UNCOMPRESSED_SIZE,__pyx_v_fnum);
    goto __pyx_L2;
  }
  /*else*/ {

    /* "k:\wow\python\extract\src\mpq.pyx":129 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    __pyx_4 = PyNumber_Remainder(__pyx_k5p, __pyx_v_fn); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
    __Pyx_Raise(__pyx_3, __pyx_4, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("mpq.File.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fn);
  Py_DECREF(__pyx_v_archive);
  return __pyx_r;
}

static PyObject *__pyx_f_3mpq_4File_close(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3mpq_4File_close(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":132 */

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("mpq.File.close");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_3mpq_4File___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3mpq_4File___del__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":135 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_close); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("mpq.File.__del__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_k6p;

static char (__pyx_k6[]) = "unable to read from file (number:%d, size:%d), errcode:%d";

static PyObject *__pyx_f_3mpq_4File_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_3mpq_4File_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_size = 0;
  char (*__pyx_v_buf);
  int __pyx_v_ret;
  PyObject *__pyx_v_s;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"size",0};
  __pyx_v_size = __pyx_k1;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|O", __pyx_argnames, &__pyx_v_size)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_size);
  __pyx_v_s = Py_None; Py_INCREF(__pyx_v_s);

  /* "k:\wow\python\extract\src\mpq.pyx":141 */
  __pyx_v_buf = malloc(((struct __pyx_obj_3mpq_File *)__pyx_v_self)->size);

  /* "k:\wow\python\extract\src\mpq.pyx":142 */
  __pyx_v_ret = libmpq_file_getdata((&((struct __pyx_obj_3mpq_File *)__pyx_v_self)->archive->mpq_a),((struct __pyx_obj_3mpq_File *)__pyx_v_self)->number,__pyx_v_buf);

  /* "k:\wow\python\extract\src\mpq.pyx":143 */
  __pyx_1 = (__pyx_v_ret < 0);
  if (__pyx_1) {

    /* "k:\wow\python\extract\src\mpq.pyx":144 */
    free(__pyx_v_buf);

    /* "k:\wow\python\extract\src\mpq.pyx":145 */
    __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_IOError); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(((struct __pyx_obj_3mpq_File *)__pyx_v_self)->number); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(((struct __pyx_obj_3mpq_File *)__pyx_v_self)->size); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    __pyx_5 = PyInt_FromLong(__pyx_v_ret); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_6, 1, __pyx_4);
    PyTuple_SET_ITEM(__pyx_6, 2, __pyx_5);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_5 = 0;
    __pyx_3 = PyNumber_Remainder(__pyx_k6p, __pyx_6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __Pyx_Raise(__pyx_2, __pyx_3, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "k:\wow\python\extract\src\mpq.pyx":146 */
  __pyx_4 = PyString_FromStringAndSize(__pyx_v_buf,((struct __pyx_obj_3mpq_File *)__pyx_v_self)->size); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; goto __pyx_L1;}
  Py_DECREF(__pyx_v_s);
  __pyx_v_s = __pyx_4;
  __pyx_4 = 0;

  /* "k:\wow\python\extract\src\mpq.pyx":147 */
  free(__pyx_v_buf);

  /* "k:\wow\python\extract\src\mpq.pyx":148 */
  Py_INCREF(__pyx_v_s);
  __pyx_r = __pyx_v_s;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("mpq.File.read");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_size);
  return __pyx_r;
}

static PyObject *__pyx_f_3mpq_4File_4name___get__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_3mpq_4File_4name___get__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "k:\wow\python\extract\src\mpq.pyx":152 */
  __pyx_1 = PyString_FromString(((struct __pyx_obj_3mpq_File *)__pyx_v_self)->mpq_f.filename); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("mpq.File.name.__get__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_IOError, "IOError"},
  {&__pyx_n_close, "close"},
  {&__pyx_n_splitlines, "splitlines"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k2p, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, __pyx_k6, sizeof(__pyx_k6)},
  {0, 0, 0}
};

static PyObject *__pyx_tp_new_3mpq_Archive(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_3mpq_Archive *p = (struct __pyx_obj_3mpq_Archive *)o;
  return o;
}

static void __pyx_tp_dealloc_3mpq_Archive(PyObject *o) {
  struct __pyx_obj_3mpq_Archive *p = (struct __pyx_obj_3mpq_Archive *)o;
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_3mpq_Archive(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_3mpq_Archive *p = (struct __pyx_obj_3mpq_Archive *)o;
  return 0;
}

static int __pyx_tp_clear_3mpq_Archive(PyObject *o) {
  struct __pyx_obj_3mpq_Archive *p = (struct __pyx_obj_3mpq_Archive *)o;
  return 0;
}

static PyObject *__pyx_getprop_3mpq_7Archive_name(PyObject *o, void *x) {
  return __pyx_f_3mpq_7Archive_4name___get__(o);
}

static PyObject *__pyx_getprop_3mpq_7Archive_blocksize(PyObject *o, void *x) {
  return __pyx_f_3mpq_7Archive_9blocksize___get__(o);
}

static PyObject *__pyx_getprop_3mpq_7Archive_size(PyObject *o, void *x) {
  return __pyx_f_3mpq_7Archive_4size___get__(o);
}

static PyObject *__pyx_getprop_3mpq_7Archive_numfiles(PyObject *o, void *x) {
  return __pyx_f_3mpq_7Archive_8numfiles___get__(o);
}

static struct PyMethodDef __pyx_methods_3mpq_Archive[] = {
  {"read", (PyCFunction)__pyx_f_3mpq_7Archive_read, METH_VARARGS|METH_KEYWORDS, 0},
  {"namelist", (PyCFunction)__pyx_f_3mpq_7Archive_namelist, METH_VARARGS|METH_KEYWORDS, 0},
  {"close", (PyCFunction)__pyx_f_3mpq_7Archive_close, METH_VARARGS|METH_KEYWORDS, 0},
  {"__del__", (PyCFunction)__pyx_f_3mpq_7Archive___del__, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyGetSetDef __pyx_getsets_3mpq_Archive[] = {
  {"name", __pyx_getprop_3mpq_7Archive_name, 0, 0, 0},
  {"blocksize", __pyx_getprop_3mpq_7Archive_blocksize, 0, 0, 0},
  {"size", __pyx_getprop_3mpq_7Archive_size, 0, 0, 0},
  {"numfiles", __pyx_getprop_3mpq_7Archive_numfiles, 0, 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Archive = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Archive = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  __pyx_f_3mpq_7Archive___contains__, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Archive = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Archive = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_3mpq_Archive = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "mpq.Archive", /*tp_name*/
  sizeof(struct __pyx_obj_3mpq_Archive), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_3mpq_Archive, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Archive, /*tp_as_number*/
  &__pyx_tp_as_sequence_Archive, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Archive, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Archive, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_3mpq_Archive, /*tp_traverse*/
  __pyx_tp_clear_3mpq_Archive, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_3mpq_Archive, /*tp_methods*/
  0, /*tp_members*/
  __pyx_getsets_3mpq_Archive, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_3mpq_7Archive___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_3mpq_Archive, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_3mpq_File(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_3mpq_File *p = (struct __pyx_obj_3mpq_File *)o;
  ((PyObject*)p->archive) = Py_None; Py_INCREF(((PyObject*)p->archive));
  return o;
}

static void __pyx_tp_dealloc_3mpq_File(PyObject *o) {
  struct __pyx_obj_3mpq_File *p = (struct __pyx_obj_3mpq_File *)o;
  Py_XDECREF(p->archive);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_3mpq_File(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_3mpq_File *p = (struct __pyx_obj_3mpq_File *)o;
  if (p->archive) {
    e = (*v)(((PyObject*)p->archive), a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_3mpq_File(PyObject *o) {
  struct __pyx_obj_3mpq_File *p = (struct __pyx_obj_3mpq_File *)o;
  Py_XDECREF(p->archive);
  ((PyObject*)p->archive) = Py_None; Py_INCREF(((PyObject*)p->archive));
  return 0;
}

static PyObject *__pyx_getprop_3mpq_4File_name(PyObject *o, void *x) {
  return __pyx_f_3mpq_4File_4name___get__(o);
}

static struct PyMethodDef __pyx_methods_3mpq_File[] = {
  {"close", (PyCFunction)__pyx_f_3mpq_4File_close, METH_VARARGS|METH_KEYWORDS, 0},
  {"__del__", (PyCFunction)__pyx_f_3mpq_4File___del__, METH_VARARGS|METH_KEYWORDS, 0},
  {"read", (PyCFunction)__pyx_f_3mpq_4File_read, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_3mpq_File[] = {
  {"archive", T_OBJECT, offsetof(struct __pyx_obj_3mpq_File, archive), READONLY, 0},
  {"size", T_UINT, offsetof(struct __pyx_obj_3mpq_File, size), READONLY, 0},
  {"number", T_INT, offsetof(struct __pyx_obj_3mpq_File, number), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static struct PyGetSetDef __pyx_getsets_3mpq_File[] = {
  {"name", __pyx_getprop_3mpq_4File_name, 0, 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_File = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_File = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_File = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_File = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_3mpq_File = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "mpq.File", /*tp_name*/
  sizeof(struct __pyx_obj_3mpq_File), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_3mpq_File, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_File, /*tp_as_number*/
  &__pyx_tp_as_sequence_File, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_File, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_File, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_3mpq_File, /*tp_traverse*/
  __pyx_tp_clear_3mpq_File, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_3mpq_File, /*tp_methods*/
  __pyx_members_3mpq_File, /*tp_members*/
  __pyx_getsets_3mpq_File, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_3mpq_4File___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_3mpq_File, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

DL_EXPORT(void) initmpq(void); /*proto*/
DL_EXPORT(void) initmpq(void) {
  PyObject *__pyx_1 = 0;
  __pyx_m = Py_InitModule4("mpq", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_3mpq_Archive) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Archive", (PyObject *)&__pyx_type_3mpq_Archive) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
  __pyx_ptype_3mpq_Archive = &__pyx_type_3mpq_Archive;
  __pyx_type_3mpq_File.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_3mpq_File) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "File", (PyObject *)&__pyx_type_3mpq_File) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  __pyx_ptype_3mpq_File = &__pyx_type_3mpq_File;

  /* "k:\wow\python\extract\src\mpq.pyx":137 */
  __pyx_1 = PyInt_FromLong((-1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_k1 = __pyx_1;
  __pyx_1 = 0;

  /* "k:\wow\python\extract\src\mpq.pyx":150 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("mpq");
}

static char *__pyx_filenames[] = {
  "mpq.pyx",
};
statichere char **__pyx_f = __pyx_filenames;

/* Runtime support code */

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    /* Next, repeatedly, replace a tuple exception with its first item */
    while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
        PyObject *tmp = type;
        type = PyTuple_GET_ITEM(type, 0);
        Py_INCREF(type);
        Py_DECREF(tmp);
    }
    if (PyString_Check(type))
        ;
    else if (PyClass_Check(type))
        ; /*PyErr_NormalizeException(&type, &value, &tb);*/
    else if (PyInstance_Check(type)) {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
              "instance exception may not have a separate value");
            goto raise_error;
        }
        else {
            /* Normalize to raise <class>, <instance> */
            Py_DECREF(value);
            value = type;
            type = (PyObject*) ((PyInstanceObject*)type)->in_class;
            Py_INCREF(type);
        }
    }
    else {
        /* Not something you can raise.  You get an exception
           anyway, just not what you specified :-) */
        PyErr_Format(PyExc_TypeError,
                 "exceptions must be strings, classes, or "
                 "instances, not %s", type->ob_type->tp_name);
        goto raise_error;
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
