//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MPQDraft.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   100
#define IDD_MPQDRAFT_DIALOG             102
#define IDS_TEAMMOPAQ                   102
#define IDS_REGKEY                      102
#define IDS_PATCHWIZARD                 103
#define IDS_SEMPQWIZARD                 104
#define IDS_OPENPATCHMPQ                105
#define IDS_OPENSEMPQMPQ                106
#define IDS_OPENMPQSETTINGS             107
#define IDS_MPQLISTHEADER               108
#define IDS_MPQFILTER                   109
#define IDS_D2MFILTER                   110
#define IDS_PATCHWIZARD3TITLE           111
#define IDS_SEMPQWIZARD3TITLE           112
#define IDI_DIABLO                      134
#define IDI_DIABLO2                     135
#define IDI_STARCRAFT                   136
#define IDI_STAREDIT                    137
#define IDI_WAR2BNE                     138
#define IDI_WAR2EDIT                    139
#define IDR_SEMPQSTUB                   143
#define IDB_MAINMENU                    144
#define IDB_SEMPQBUTTONUP               145
#define IDB_SEMPQBUTTONDOWN             146
#define IDB_PATCHBUTTONUP               147
#define IDB_PATCHBUTTONDOWN             148
#define IDB_XBUTTONUP                   153
#define IDB_MINBUTTONUP                 154
#define IDB_XBUTTONDOWN                 155
#define IDB_MINBUTTONDOWN               156
#define IDB_WIZARD                      157
#define IDR_MPQDRAFTDLL                 159
#define IDR_PATCHERDLL                  159
#define IDB_SGBUTTONON                  160
#define IDB_SGBUTTONOFF                 161
#define IDB_SCEXBUTTON                  162
#define IDR_STARGRAFTDLL                163
#define IDR_SGDLL                       163
#define IDR_SGVERSION                   164
#define IDI_PLUGIN                      166
#define IDI_MPQ                         167
#define IDI_WARCRAFT3                   169
#define IDI_LOMSE                       170
#define IDI_HELLFIRE                    171
#define IDI_WAR3HEADER                  172
#define IDI_WAR3EDIT                    173
#define IDI_WAR3X                       174
#define IDS_OPENPATCHTARGET             201
#define IDS_OPENSEMPQTARGET             202
#define IDS_SAVESEMPQ                   203
#define IDS_OPENEXESETTINGS             204
#define IDS_DEFEXEEXT                   205
#define IDS_SELECTSEMPQICON             206
#define IDS_OPENICONSETTINGS            207
#define IDD_MAINMENU                    266
#define IDD_SELECTPROGRAMPAGE           267
#define IDD_PATCHTARGETPAGE             267
#define IDD_PATCHWIZARD2                268
#define IDD_SEMPQWIZARD1                269
#define IDD_SEMPQWIZARD22               282
#define IDS_CANTLOADDEFICON             301
#define IDS_TOOMANYMPQS                 302
#define IDS_NOSEMPQTARGET               303
#define IDS_NOPATCHTARGET               304
#define IDS_ODDSEMPQTARGET              305
#define IDS_PATCHFAILED                 306
#define IDS_SEMPQFAILED                 307
#define IDS_SEMPQCAPTION                401
#define IDS_WRITINGEXE                  402
#define IDS_WRITINGMPQ                  403
#define IDS_CANTCREATEFILE              405
#define IDS_BADMPQ                      406
#define IDS_CANTOPENMPQ                 407
#define IDS_CANTOPENFILE                407
#define IDS_CANTMALLOC                  408
#define IDS_CANTEXTRACTDLL              409
#define IDS_INTERNALERROR               409
#define IDS_CANTWRITE                   410
#define IDS_NOSEMPQNAME                 411
#define IDS_NOSEMPQMPQ                  412
#define IDS_NOSEMPQFILENAME             413
#define IDS_USEDEFSEMPQICON             414
#define IDS_PATCHKEY                    415
#define IDS_SEMPQKEY                    416
#define IDS_SELAPPKEY                   417
#define IDS_SELFILEKEY                  418
#define IDS_APPPATHKEY                  419
#define IDS_USEPATHKEY                  420
#define IDS_MPQDIRKEY                   421
#define IDS_SEMPQPATHKEY                422
#define IDS_TGTPATHKEY                  423
#define IDS_ICONPATHKEY                 424
#define IDS_SRCPATHKEY                  425
#define IDS_SEMPQNAMEKEY                426
#define IDS_OPENSGPAT                   427
#define IDS_OPENPLUGIN                  427
#define IDS_OPENSGPATSETTINGS           428
#define IDS_OPENPLUGINSETTINGS          428
#define IDS_SGPATKEY                    429
#define IDS_PLUGINDIRKEY                429
#define IDS_CANTLOCATE                  430
#define IDS_TOOMANYPLUGINS              431
#define IDS_PLUGINVALUETEMPLATE         432
#define IDS_PLUGINDATATEMPLATE          433
#define IDS_PLUGINFILTER                434
#define IDS_PLUGINLISTTEMPLATE          435
#define IDS_PLUGINLISTHEADER            436
#define IDS_WINDOWSERROR                437
#define IDS_WRITINGPLUGINS              438
#define IDS_PLUGINNOTREADY              439
#define IDS_REDIRWARNING                440
#define IDS_REDIROPENFILEEXKEY          441
#define IDS_PARAMETERSKEY               442
#define IDS_PATCHWIZARD1TITLE           443
#define IDS_SEMPQWIZARD2TITLE           444
#define IDS_PATCHWIZARD1INFO            445
#define IDS_SEMPQWIZARD2INFO            446
#define IDC_INFORMATION                 999
#define IDC_CREATESEMPQ                 1000
#define IDC_EXENAME                     1000
#define IDC_LOADMPQS                    1001
#define IDC_TITLE                       1002
#define IDC_MINIMIZE                    1002
#define IDC_CREDITS                     1003
#define IDC_CLOSE                       1003
#define IDC_PROGRAMSLABEL               1004
#define IDC_ENABLESG                    1004
#define IDC_STARGRAFT                   1004
#define IDC_PROGRAMS                    1005
#define IDD_SEMPQPROGRESS               1005
#define IDC_STAREX                      1005
#define IDC_COMPONENTLABEL              1006
#define IDC_SGFRAME                     1006
#define IDD_SEMPQWIZARD33               1006
#define IDC_COMPONENTS                  1007
#define IDC_PATFILELABLE                1007
#define IDD_PATCHWIZARD3                1007
#define IDD_PLUGINPAGE                  1007
#define IDC_FILENAMELABLE               1008
#define IDC_PROGRESS                    1008
#define IDC_PATFILENAME                 1008
#define IDD_OLDPATCHWIZARD3             1008
#define IDC_FILENAME                    1009
#define IDC_BROWSEFORPAT                1009
#define IDC_BROWSE                      1010
#define IDC_ICONLABEL                   1010
#define IDC_STARGRAFTINFO               1010
#define IDC_MPQSLABEL                   1011
#define IDC_FILENAME2                   1011
#define IDC_ICONNAME                    1011
#define IDC_SGFRAME2                    1011
#define IDC_CONFIGURE                   1011
#define IDC_LIST1                       1012
#define IDC_MPQNAME                     1012
#define IDC_MPQS                        1012
#define IDC_STARGRAFTINFO2              1012
#define IDC_NAMELABEL                   1013
#define IDC_MOVEUP                      1013
#define IDC_SCEXFILELABLE               1013
#define IDC_PLUGINS                     1013
#define IDC_SEMPQNAME                   1014
#define IDC_MOVEDOWN                    1014
#define IDC_SCEXFILENAME                1014
#define IDC_REDIROPENFILEEX             1014
#define IDC_BROWSEFILENAME              1015
#define IDC_BROWSEEXE                   1015
#define IDC_BROWSEFORSCEX               1015
#define IDC_ICONDISPLAY                 1016
#define IDC_PARAMETERS                  1016
#define IDC_BROWSEICON                  1017
#define IDC_ICONDISPLAY2                1017
#define IDC_PARAMSLABEL                 1017
#define IDC_FILENAMELABEL               1018
#define IDC_EXENAMELABEL                1018
#define IDC_MPQNAMELABEL                1019
#define IDC_BROWSEMPQ                   1020
#define IDC_STATUS                      1029
#define IDC_FRAME                       1139

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
